name: Update Changelog

on:
  push:
    branches:
      - main
      - dev

jobs:
  update_changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Generate Changelog
      uses: mikepenz/release-changelog-builder-action@v2
      with:
        configuration: .github/release-config.yml
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit and Push Changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add CHANGELOG.md
        git commit -m "Update changelog"
        git push